"""Writes what the game needs from the map scenes:
  src/server/Maps/Scenes/<Venue>.luau  colliders, props, lights, signs and emitters per venue
  src/shared/SceneMaterials.luau        how the game dresses each flat material
  art/export/InkboundMaps.fbx           every scene mesh (with its textures) plus three
                                        calibration cubes the game uses to undo whatever scale
                                        and rotation the importer applied
"""

import os

import bpy

import common
from maps import matlib

SCENES_DIR = os.path.join(common.ROOT, "src", "server", "Maps", "Scenes")
MATERIALS_LUAU = os.path.join(common.ROOT, "src", "shared", "SceneMaterials.luau")
FBX = os.path.join(common.EXPORT, "InkboundMaps.fbx")

# Calibration cubes: their centres sit at these Roblox positions in the scene space.
CALIBRATION = {"Calib_Maps_O": (0, 0, 0), "Calib_Maps_X": (64, 0, 0), "Calib_Maps_Y": (0, 64, 0)}


def num(v, digits=3):
    text = f"{v:.{digits}f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def vec(values, digits=3):
    return "{ " + ", ".join(num(v, digits) for v in values) + " }"


def rgb(values):
    return "{ " + ", ".join(str(int(v)) for v in values) + " }"


def lua_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def write_scene(scene, source):
    os.makedirs(SCENES_DIR, exist_ok=True)
    lines = [
        "--!strict",
        f"-- GENERATED by art/scripts/run_maps.py from {source}. Do not edit by hand.",
        f"-- The {scene.venue} scene: the meshes are Scene_{scene.venue}_* in the imported InkboundMaps.fbx;",
        "-- this lists what the game adds around them (positions are local to the venue's origin).",
        "",
        "return {",
        "\t-- x, y, z, size x, y, z, degrees about Y, blocks sight lines",
        "\tcolliders = {",
    ]
    for c in scene.colliders:
        x, y, z, sx, sy, sz, rot, query = c
        lines.append(f"\t\t{{ {num(x)}, {num(y)}, {num(z)}, {num(sx)}, {num(sy)}, {num(sz)}, {num(rot, 2)}, "
                     f"{'true' if query else 'false'} }},")
    lines.append("\t},")
    lines.append("\t-- prop, x, y, z, degrees about Y, scale")
    lines.append("\tprops = {")
    for key, x, y, z, rot, sc in scene.props:
        lines.append(f'\t\t{{ "{key}", {num(x)}, {num(y)}, {num(z)}, {num(rot, 2)}, {num(sc)} }},')
    lines.append("\t},")
    lines.append("\tlights = {")
    for li in scene.lights:
        lines.append(
            f'\t\t{{ kind = "{li["kind"]}", at = {vec(li["pos"])}, color = {rgb(li["color"])}, '
            f'range = {num(li["range"], 1)}, brightness = {num(li["brightness"], 2)}, '
            f'shadows = {"true" if li["shadows"] else "false"}, face = "{li["face"]}", angle = {num(li["angle"], 1)}, '
            f'flicker = {"true" if li["flicker"] else "false"} }},'
        )
    lines.append("\t},")
    lines.append("\tsigns = {")
    for sg in scene.signs:
        bg = rgb(sg["bg"]) if sg["bg"] else "nil"
        glow = rgb(sg["glow"]) if sg["glow"] else "nil"
        lines.append(
            f'\t\t{{ at = {vec(sg["pos"])}, rot = {num(sg["rot"], 2)}, w = {num(sg["w"])}, h = {num(sg["h"])}, '
            f'text = {lua_string(sg["text"])}, font = "{sg["font"]}", color = {rgb(sg["color"])}, bg = {bg}, '
            f'glow = {glow}, align = "{sg["align"]}" }},'
        )
    lines.append("\t},")
    lines.append("\temitters = {")
    for em in scene.emitters:
        lines.append(f'\t\t{{ kind = "{em["kind"]}", at = {vec(em["pos"])}, rot = {num(em["rot"], 2)} }},')
    lines.append("\t},")
    lines.append("}")
    path = os.path.join(SCENES_DIR, scene.venue + ".luau")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    return path


def write_materials(used):
    with open(MATERIALS_LUAU, "w", encoding="utf-8", newline="\n") as f:
        f.write(matlib.luau_table(used))
    return MATERIALS_LUAU


def calibration_cubes(collection):
    objects = []
    for name, (x, y, z) in CALIBRATION.items():
        old = bpy.data.objects.get(name)
        if old:
            bpy.data.objects.remove(old, do_unlink=True)
        mesh = bpy.data.meshes.new(name)
        h = 0.5
        verts = [(-h, -h, -h), (h, -h, -h), (h, h, -h), (-h, h, -h), (-h, -h, h), (h, -h, h), (h, h, h), (-h, h, h)]
        faces = [(0, 3, 2, 1), (4, 5, 6, 7), (0, 1, 5, 4), (1, 2, 6, 5), (2, 3, 7, 6), (3, 0, 4, 7)]
        mesh.from_pydata(verts, [], faces)
        mesh.uv_layers.new(name="UVMap")
        mesh.materials.append(matlib.material("BlackTrim"))
        obj = bpy.data.objects.new(name, mesh)
        obj.location = (-x, z, y)  # Roblox -> Blender
        collection.objects.link(obj)
        objects.append(obj)
    return objects


def export_fbx(objects):
    bpy.ops.object.select_all(action="DESELECT")
    for obj in objects:
        obj.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    bpy.ops.export_scene.fbx(
        filepath=FBX,
        use_selection=True,
        object_types={"MESH"},
        apply_unit_scale=True,
        apply_scale_options="FBX_SCALE_ALL",
        axis_forward="Z",
        axis_up="Y",
        bake_space_transform=True,
        use_mesh_modifiers=True,
        mesh_smooth_type="FACE",
        use_tspace=True,
        path_mode="COPY",
        embed_textures=True,
        add_leaf_bones=False,
    )
    return FBX
